[project]
name = "bratpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.6",
    "rapidfuzz>=3.12.1",
    "ruff>=0.9.4",
    "streamlit>=1.42.0",
    "typing>=3.10.0.0",
]
